spring.application.name=backend
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

openweather.api.key=${OPENWEATHER_API_KEY:}
openweather.api.url=${OPENWEATHER_BASE_URL:https://api.openweathermap.org/data/2.5/weather}

pexels.api.key=${PEXELS_API_KEY:}
pexels.api.url=${PEXELS_BASE_URL:https://api.pexels.com/v1/search}

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent}
